name: Build Renpy Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v6
      # 安装 JDK 环境
      - name: Install Java toolchain
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      # 安装 Android 环境
      - name: Install Android toolchain
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
      # 安装 Python 环境
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      # 安装 Renpy 环境
      - name: Setup Ren'Py
        uses: remarkablegames/setup-renpy@v2
        with:
          cli-version: 8.5.2
          rapt: true
      # 开始构建 Android
      - name: Run Build
        run: |
          renpy-launcher android_build . --destination ./build
      # 上传工件
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: android-build
          path: ./build